# To find available Node images, see https://mcr.microsoft.com/en-us/product/devcontainers/javascript-node/tags

# [Choice] Node.js version
ARG VARIANT="dev-24-bullseye"# To find available Node images, see https://mcr.microsoft.com/en-us/product/devcontainers/javascript-node/tags

# [Choice] Node.js version
ARG VARIANT="dev-24-bullseye"
FROM mcr.microsoft.com/devcontainers/javascript-node:${VARIANT}
FROM mcr.microsoft.com/devcontainers/javascript-node:${VARIANT}
